### ISSUE TITLE
Fan time calculation error

### ISSUE THREAD

**Issue by sup-one** [beestat/app#101] opened 2019-03-19 14:44 UTC
There seems to be an error in fan time calculation.  Below is an example of what my fan time looked like for Mar 18 based on 30 min/hr schedule that Ecobee created, but beestat shows as a continuous run time.

22:30:00	60
22:35:00	300
22:40:00	90
22:45:00	60
22:50:00	300
22:55:00	90
23:00:00	60
23:05:00	300
23:10:00	90
23:15:00	60
23:20:00	300
23:25:00	90
23:30:00	60
23:35:00	300
23:40:00	90
23:45:00	60
23:50:00	300
23:55:00	90
0:00:00	60
0:05:00	300
0:10:00	90
0:15:00	60
0:20:00	300
0:25:00	90
0:30:00	60
0:35:00	300
0:40:00	90
0:45:00	60
0:50:00	300
0:55:00	90
1:00:00	60
1:05:00	300
1:10:00	90
1:15:00	60
1:20:00	300
1:25:00	90
1:30:00	60
1:35:00	300
1:40:00	90
1:45:00	60
1:50:00	300
1:55:00	90
2:00:00	60
2:05:00	300
2:10:00	90
2:15:00	60
2:20:00	300
2:25:00	90
2:30:00	60
2:35:00	300
2:40:00	90
2:45:00	60
2:50:00	300
2:55:00	90
3:00:00	60
3:05:00	300
3:10:00	90
3:15:00	60
3:20:00	300
3:25:00	90

**Comment by ziebelje** [comment] 2019-03-27 13:29
I see the issue. For any of the bars up top they are filled in for the complete five minute segment if the fan was on at all during those five minutes. So in your case the fan just appears to always be on, even though it's shutting off for a little while. Would you mind to share a screenshot of how that appears on your Home IQ?

I'm also a little bit concerned about your fan runtimes. According to your data, your fan is doing this:

On for 6.5 minutes
Off for 3.5 minutes
On for 1 minute
Off for 4 minutes
...
Repeat

If that's correct then you're getting a ton of wear and tear...the behavior also doesn't make much sense.

**Comment by sup-one** [comment] 2019-03-27 18:55
Jon,

Visually it looks like a solid block but each 5 min slot shows how much
time the fan was ON.  Ecobee created the schedule 7.5 min ON, 7.5 min OFF
for 30min per hour.  I am lowering the number to 20min - this helps with
air circulation around the house and refreshing basement stale air,
especially when HVAC is not running.

Oskar

**Comment by ziebelje** [comment] 2019-04-05 01:02
Fixing this is actually relatively difficult as I'll have to change a number of things about how that graph is generated. I'll get to it but assigning a pretty low priority on it at the moment. Thanks for reporting the issue!

**Comment by ziebelje** [comment] 2019-07-26 18:36
Closing as a duplicate of #121. I kind of have this working but have not committed the time to sit down and finish this. Should actually happen though.

**Closed by ziebelje** 2019-07-26 18:36 UTC
Labels: 🐞 Bug
