### ISSUE TITLE
Log individual sensor temperatures

### ISSUE THREAD

**Issue by gbronner** [beestat/app#156] opened 2019-10-17 16:12 UTC
Hi,

I have a one-zone heating system with four sensors. I'd like to be able to at historical temperature graphs by sensor.

**Comment by ziebelje** [comment] 2019-10-18 01:33
Duplicate of #17. The update going live tomorrow is addressing the data storage concerns I had about this. Syncing sensor data is next up.

**Closed by ziebelje** 2019-10-18 01:33 UTC
Labels: Duplicate
