### ISSUE TITLE
Temperature and Sensor Plots are Stuck on Syncing 

### ISSUE THREAD

**Issue by GregZimmerman** [beestat/app#333] opened 2021-03-15 13:26 UTC
Since Saturday night / Sunday morning, the temperature and sensor detail graphs are stuck syncing. Is this a known issue or is something sideways just with my system?  
![Screen Shot 2021-03-15 at 8 23 02 AM](https://user-images.githubusercontent.com/80693367/111160155-d533ce80-8567-11eb-9785-1be101fb07d2.png)

**Comment by ziebelje** [comment] 2021-03-15 13:27
Closing as duplicate of #332 

This issue should be resolved now.

**Closed by ziebelje** 2021-03-15 13:27 UTC
Labels: Duplicate
