### ISSUE TITLE
Connecting fails if you are not the primary user on the ecobee account

### ISSUE THREAD

**Issue by alex-taffe** [beestat/app#309] opened 2020-12-08 15:33 UTC
When I go to login to beestat.io, I login via oauth to my ecobee account, but then the website appears to hang. Eventually it loads to a totally blank page. If I refresh, I’m greeted with:
```
{"success":false,"data":{"error_message":"The request is malformed. Check parameters.","error_code":10505}}
```
The URL for this page is:
```
https://app.beestat.io/api/?resource=ecobee&method=initialize&arguments=%7B%22code%22:%22Yqfs2FJyXW8a51vh%22%7D&api_key=REDCATED
```

**Comment by ziebelje** [comment] 2021-01-18 17:49
Hey Alex,

Did you get this working? If not, it might take a bit of investigation and tracking down a few things from my logs.

**Comment by alex-taffe** [comment] 2021-01-18 17:52
@ziebelje I have not, it's still throwing the same error back

**Comment by ziebelje** [comment] 2021-01-18 17:56
I'll turn on some verbose error logging tonight and have you try again.

**Comment by alex-taffe** [comment] 2021-01-18 18:51
Ok thanks, just let me know

**Comment by ziebelje** [comment] 2021-01-21 02:05
Can you send me your thermostat serial number? You can email it to contact@beestat.io.

I can't turn on the level of debugging I need for everyone or bad things will happen but I can flip it on for your user.

**Comment by alex-taffe** [comment] 2021-01-21 02:12
@ziebelje I just emailed it, although I'm not sure it will help just because I've not even successfully authed with the app before, so I'm not sure if it has ever captured my serial number

**Comment by ziebelje** [comment] 2021-01-21 02:15
(－‸ლ)

True.

I just flipped global debugging on. Can you try authorizing again?

**Comment by alex-taffe** [comment] 2021-01-21 02:18
@ziebelje just tried it at 9:17-9:18pm EST

**Comment by ziebelje** [comment] 2021-01-21 02:46
Ecobee is returning an empty list of thermostats when it tries to sync and everything is blowing up as I'm not really accounting for that. Are you enrolled with ecobee's SmartBuildings product? That is the only thing I am currently aware of that causes this.

**Comment by alex-taffe** [comment] 2021-01-21 02:49
@ziebelje I am not, I hadn't even heard of that until you just mentioned it. One thing I can think of is I'm not the homeowner on the account, but that being said I have full access to everything on the official ecobee website so I'm not sure

**Comment by ziebelje** [comment] 2021-01-21 02:52
That's interesting. Are you able to log in using the primary account? I suspect this may be a permissions issue on ecobee's end but would love to verify if you're able.

**Comment by ziebelje** [comment] 2021-01-21 11:43
For my own reference, here's ecobee's response to the thermostat request:
```
{
  "page": {
    "page": 1,
    "totalPages": 0,
    "pageSize": 0,
    "total": 0
  },
  "thermostatList": [],
  "status": {
    "code": 0,
    "message": ""
  }
}
```

**Comment by ziebelje** [comment] 2021-01-21 19:06
Another user with the issue here: https://community.beestat.io/t/unable-to-register-ecobee-to-beestat/295/5

Confirmed that, for them, using the primary account with beestat works.

**Comment by Ray-B** [comment] 2021-01-21 19:58
This is weird problem. I filed a ticket with developer support to get their feedback for my own sanity, so I hope that is OK. I kept it vague as im not project contributor here, but I was curious what they have to say.  Seems really dumb for the API to return an empty list when it should be returning a 403.

In the meantime - having a look at the code, I see this: https://github.com/beestat/app/blob/c40c43c16f5613f0a732843dfa2e20a15c700ef5/api/ecobee.php#L42

`$ecobee_token = $this->api('ecobee_token', 'obtain', ['code' => $code]);`

Presumably, if a token is being generated, and the subsequent GET to /thermostat on line 45 is returning 200 with an empty list, then all the prior authorization steps for allowing beestat access to a user's account must have succeeded...


Handling the scenario of an empty list gracefully makes a lot of sense: https://github.com/beestat/app/blob/c40c43c16f5613f0a732843dfa2e20a15c700ef5/api/ecobee.php#L63

It would sort of protect from this issue - but I think ecobee needs chime in. 


Throwing mud on the wall: Maybe there is an endpoint that can be called to check details about user to see if they have the right permissions for certain operations.

**Comment by Ray-B** [comment] 2021-01-21 21:04
I spoke with the EcoBee team, and one of their devs kindly pointed out a nuance. _I'll omit his name since I didn't get permission to use it._ 

But this looks like it could be the source of the problem: https://github.com/beestat/app/blob/c40c43c16f5613f0a732843dfa2e20a15c700ef5/api/ecobee.php#L51

If a call to get thermostats for a non-primary account user is requesting "registered" thermostats, the API is always going to return an empty list, because only primary account users can register devices. 

Should try setting that to false and I bet it will return data...

**Comment by ziebelje** [comment] 2021-01-21 21:21
Their [documentation](https://www.ecobee.com/home/developer/api/documentation/v1/objects/Selection.shtml) suggests the only useful values here are "registered" or "thermostats".

The documentation also seems to indicate that the selectionMatch parameter must be non-empty when doing that, which defeats the purpose of this API call as I don't know the serial numbers yet. However, there's an example on [another page](https://www.ecobee.com/home/developer/api/documentation/v1/operations/get-thermostats.shtml) of their documentation that leaves selectionMatch empty.

I'll give this a whirl tonight and see what the results are. Thanks for digging into this.

**Comment by alex-taffe** [comment] 2021-01-26 00:38
@ziebelje sorry this got buried in my email. I just confirmed with the primary account, I am able to login properly

**Comment by ziebelje** [comment] 2021-01-27 22:41
I can confirm that setting selectionType to "thermostats" does not have the desired effect. It requires specifying thermostat identifiers. I don't know of any way to get a list of all thermostat identifiers you have access to, so the only way I can think to make this work at the moment is to allow you to manually specify them.

This isn't ideal, so I opened a ticket with ecobee to see if they have any thoughts. @Ray-B, which channel did you go through to get a response so quickly? I've always had trouble getting responses from the normal support channels.

**Comment by ziebelje** [comment] 2021-02-23 12:00
Ecobee confirmed that there is no way to enumerate a list of thermostats that you don't own but have access to. So basically any shared thermostats. The only way I can resolve this is by adding the ability to manually add thermostats to your account.

**Comment by ziebelje** [comment] 2021-02-23 12:03
That makes this not a bug since the ecobee API is working as designed. I am moving this feature request here: https://community.beestat.io/t/add-way-to-manually-add-thermostats/475

**Closed by ziebelje** 2021-02-23 12:03 UTC
Labels: Bug
