### ISSUE TITLE
Request ability to filter which sensors are used for temperature profiles

### ISSUE THREAD

**Issue by alohawolf** [beestat/app#393] opened 2023-05-08 23:18 UTC
I think the existing application uses a composite of the temperature sensors installed in the system - on a per thermostat basis.

This leaves me with some wildly different results - I have one room that is consistently hot because of a computer in the room, but it seems to cause an issue with temperature profiles - I have a multi-system house, and I get vastly different temperature profiles between the north end and south end of the house even though system runtime, etc, is broadly similar.

The only reason I can theorize for this is that beestat is using a composite for all temperature sensors rather than the system indicated temp (based on which sensors are active per comfort profile or follow me settings).

It'd be nice to tell beestat to ignore results from different sensors (sensors I want to graph but dont use to otherwise meter the AC).

It'd also be nice with this functionality, if I could get a combine temp sensor based on all thermostats in the house rather than it being per thermostat as it is currently.

**Comment by ziebelje** [comment] 2023-05-10 10:43
> I think the existing application uses a composite of the temperature sensors installed in the system - on a per thermostat basis.
This is true.

> The only reason I can theorize for this is that beestat is using a composite for all temperature sensors rather than the system indicated temp (based on which sensors are active per comfort profile or follow me settings).
This is not.

The beestat temperature profiles use the thermostat-displayed temperature. This is an average of all sensors currently participating in your temperature profile. There's some other minor logic to help keep things clean, but that's the data it starts with.

There is an open feature request for having [per-sensor profiles](https://community.beestat.io/t/separate-temperature-profiles-for-each-sensor-or-other-insights-for-tuning-hvac-system/297) (not the same as your request, but similar). Something like that might help track down the cause.

**Comment by ziebelje** [comment] 2023-06-12 10:57
Closing in favor of the feature request linked above.

**Closed by ziebelje** 2023-06-12 10:57 UTC
Labels: Analyze
