### ISSUE TITLE
Custom Comfort Settings not showing their colored bar in Recent Activity graph

### ISSUE THREAD

**Issue by ck42** [beestat/app#70] opened 2018-11-06 15:49 UTC
I have two custom Comfort Settings I've created.
In the Recent Activity graph, when those comfort settings time windows are active, there is not colorized bar indicated (And no "Follow Me" value is shown for these custom comfort settings in the mouse-over window.  In fact, the "Follow Me" verbiage is even completely missing during these periods in the mouse-over window)

**Comment by ziebelje** [comment] 2018-11-06 16:07
Duplicate of #65. :)

**Closed by ziebelje** 2018-11-06 16:07 UTC
Labels: Duplicate

**Comment by ck42** [comment] 2018-11-06 16:09
Arghh...I did do a quick preliminary search to try to prevent a dupe post.  Somehow I missed it.  Sorry.
